---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    chocolatey_packages:
      - putty.install
      - { name: mobaxterm, ignore_checksums: true }

  tasks:
    - name: Include role 'ansible-role-chocolatey'
      ansible.builtin.include_role:
        name: ansible-role-chocolatey
