---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    chocolatey_packages: ['mobaxterm', 'putty.install']
  tasks:
    - name: Include role 'ansible-role-chocolatey'
      ansible.builtin.include_role:
        name: ansible-role-chocolatey
